### ISSUE TITLE
Custom Custom Data...

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/cleanslate-cms#234]
Would it be possible for certain custom data attributes to be in the form of a drop-down menu with predefined options, or as a check box, rather than a text field? That would be really cool.

**Comment by nreckart** [comment]
Sure, anything is possible. It would make the things more complicated. Where and how would the predefined options be defined? Where would the type of field (text box, drop-down, check-box, etc.) be defined? And you'd probably what this to be available for all types of custom data (page, site, and theme), correct?

**Comment by adamjohnson** [comment]
Perhaps something like this in `config.yml`, and template frontmatter:

```yaml
custom_site_attributes:
  - google_site_verification
    type: text
    title: "Google site verification"
    description: "Paste the code you got from Google Search Console into this box."

  - nav_depth
    type: select
    title: "Navigation Depth"
    description: "How many levels deep to you want your main navigation?"
    options:
      - 1
      - 2
      - 3
```
If `type` isn't defined, it defaults to `text`. 

These would be displayed in Page Properties > Custom Data.
